export const personnesMock = [
  {
    name: 'Jamel',
    firstname: 'Kamel',
    cin: 123456,
    job: 'Engineer',
    path: '',
    age: 35,
    id: 1,
  },
  {
    name: 'Sarah',
    firstname: 'Ben Sarah',
    cin: 987654,
    job: 'Doctor',
    path: '',
    age: 30,
    id: 2,
  },
  {
    name: 'Karim',
    firstname: 'Karim',
    cin: 13579246,
    job: 'Lawyer',
    path: '',
    age: 40,
    id: 3,
  },
  {
    name: 'Fatima',
    firstname: 'Bint Fatima',
    cin: 35791357,
    job: 'Teacher',
    path: '',
    age: 38,
    id: 4,
  },
  {
    name: 'Ahmed',
    firstname: 'Ben Ahmed',
    cin: 57935793,
    job: 'Policeman',
    path: '',
    age: 33,
    id: 5,
  },
];
